CCOMP = gcc
CFLAGS = -o
SOURCES = main.c Sources/struct_stack.c Sources/file_handling.c

TARGET = matchingParentheses

all:
	$(CCOMP) $(CFLAGS) $(TARGET) $(SOURCES)

clean:
	del $(TARGET).exe